typography_spectrum: 0.13571
color:
  brandColors:
    - '#1a1a1a'
    - '#ffffff'
    - '#4b4b4b'
    - '#d7d7d7'
    - '#818181'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07222
analytics:
  google: UA-50690855-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9850a67b-43ff-47df-a676-0410af14258b.png
name: MAYDAY
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: WHAT WE DO
    id: b6f0871b-0784-4183-ae7d-6a21902b4e40
    type: content
favicon: null
title: MAYDAY
description: Branding & Brand Experience Agency
purpose: []
