name: Mayday
favicon: null
layout_spectrum: 0.75168
typography_spectrum: 0.13571
title: 'MAYDAY // Branding & Brand Experience Agency'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#ffffff'
    - '#4b4b4b'
    - '#d7d7d7'
    - '#818181'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
