typography_spectrum: 0.13571
color:
  brandColors:
    - '#1a1a1a'
    - '#ffffff'
    - '#4b4b4b'
    - '#d7d7d7'
    - '#818181'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07222
analytics:
  google: UA-50690855-1
  facebook: null
  twitter: null
name: MAYDAY
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: MAYDAY
description: Branding & Brand Experience Agency
purpose: []
