name: Mayday
favicon: null
layout_spectrum: 0.50261
typography_spectrum: 0.13571
title: 'MAYDAY // Branding & Brand Experience Agency'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50690855-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#ffffff'
    - '#4b4b4b'
    - '#d7d7d7'
    - '#818181'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
