name: Mayday
favicon: null
layout_spectrum: 0.57319
typography_spectrum: 0.66069
title: 'Branding & Design Agency'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#ffffff'
    - '#4b4b4b'
    - '#d7d7d7'
    - '#818181'
  brandStrength: 1
  lightness: 0.010093649383634329
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
